export class DetailMarketingOrder {
  detailId: Number;
  moId: string;
  itemCuring: string;
  category: String;
  partNumber: number;
  description: String;
  machineType: String;
  capacity: Number;
  qtyPerMould: Number;
  spareMould: number;
  mouldMonthlyPlan: number;
  qtyPerRak: number;
  minOrder: number;
  maxCapMonth0: number;
  maxCapMonth1: number;
  maxCapMonth2: number;
  initialStock: Number;
  sfMonth0: Number;
  sfMonth1: Number;
  sfMonth2: Number;
  moMonth0: number;
  moMonth1: number;
  moMonth2: number;
  ppd: Number;
  cav: Number;
  status: Number;
  lockStatusM0: number;
  lockStatusM1: number;
  lockStatusM2: number;
  ar: number;
  defect: number;
  reject: number;
  // Optional properties for tracking input state
  totalAr?: number = 0;
  ArMoM1: number = 0;
  RjMoM1: number = 0;
  isTouchedM0?: boolean = false;
  isTouchedM1?: boolean = false;
  isTouchedM2?: boolean = false;
  isTouchedMinOrder: boolean = false;
  isInvalid1? : boolean = false;
  validationMessageM0: string = '';
  validationMessageM1: string = '';
  validationMessageM2: string = '';
  selected?: boolean; 
}
